stages:
  - build

windows-build:
  stage: build
  tags:
    - windows
  script:
    - cmake -S . -B build -G "Visual Studio 17 2022" -A x64
    - cmake --build build --config Release
  artifacts:
    name: "TrayWin32App-windows-x64"
    paths:
      - build/Release/TrayWin32App.exe
    expire_in: 1 week
