name: Java CI with Maven and SSL

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SSL_PASSWORD: ${{ secrets.SSL_PASSWORD }}

      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      JWT_SECRET: ${{ secrets.JWT_SECRET }}

      SIGNATURE_KEY_STORE_PASSWORD: ${{ secrets.SIGNATURE_KEY_STORE_PASSWORD }}
      SIGNATURE_KEY_PASSWORD: ${{ secrets.SIGNATURE_KEY_PASSWORD }}
      SIGNATURE_KEY_ALIAS: ${{ secrets.SIGNATURE_KEY_ALIAS }}

      SIGNATURE_PUBLIC_KEY: ${{ vars.SIGNATURE_PUBLIC_KEY }}

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Decode SSL keystore
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > src/main/resources/staviskiy_server.jks

      - name: Decode signature keystore
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.SIGNATURE_KEYSTORE_BASE64 }}" | base64 --decode > src/main/resources/signing.p12

      - name: Build with Maven
        run: mvn -DskipTests clean package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tourism-service-secure
          path: target/*.jar